# -*- coding: utf-8 -*-
"""NBA stat tracker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oaVvK_tdAQwxkeIZPnPrB4c8YcR2slI_
"""

# ============================================
# Nba Player Stat Analysis
# Author: Doyin Oyedijo
# Description: Analyzes stats from all_seasons.csv
# by player stats
# ============================================
import zipfile
import pandas as pd

# ---- STEP 1: Convert csv in zip, read from zip, and transform into a data set ----
with zipfile.ZipFile('/content/all_seasons.csv.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/')

Playerstats= pd.read_csv('all_seasons.csv')
Playerstats['player_weight']= round(Playerstats['player_weight'],2)


# ---- STEP 2: Sort data set, for the stats we will be tracking by ----

pts = Playerstats.sort_values(by='pts',ascending=False)

ast = Playerstats.sort_values(by='ast',ascending=False)

reb = Playerstats.sort_values(by='reb',ascending=False)

Playerstats['PRA'] = Playerstats['pts'] + Playerstats['reb'] + Playerstats['ast']

pra = Playerstats.sort_values(by='PRA', ascending = False).round()

season_stats = Playerstats.groupby('season')[['pts','ast','reb']].mean().round()

# ---- STEP 3: Clean and Analyze Data ----

def analyze(Playerstats):

  print('=== PLAYER STATS ===')
  print(f"Total amount of players: {len(Playerstats['player_name'].unique())}")
  print(f"Average per season points:{season_stats}")
  print(f"Top Scorer: {pts.iloc[0]['player_name']} - {pts.iloc[0]['pts']} pts")
  print(f"Top Passer: {ast.iloc[0]['player_name']} - {ast.iloc[0]['ast']} ast")
  print(f"Top Rebounder: {reb.iloc[0]['player_name']} - {reb.iloc[0]['reb']} reb")
  print(f"Bottom Scorer: {pts.iloc[-1]['player_name']} - {pts.iloc[-1]['pts']} pts")
  print(f"Bottom Passer: {ast.iloc[-1]['player_name']} - {ast.iloc[-1]['ast']} ast")
  print(f"Bottom Rebounder: {reb.iloc[-1]['player_name']} - {reb.iloc[-1]['reb']} reb")
  print(f"Highest pts-reb-ast: {pra.iloc[0]['player_name']} - {pra.iloc[0]['PRA']}")
  print(f"Lowest pts-reb-ast: {pra.iloc[-1]['player_name']} - {pra.iloc[-1]['PRA']}")
  print(f"Most consistent scorer: {Playerstats.groupby('player_name')['pts'].std().idxmin()}")
  print(f"Highest scoring team: {Playerstats.groupby('team_abbreviation')['pts'].mean().idxmax()}")
  print(f"Highest scoring season: {Playerstats.groupby('season')['PRA'].mean().idxmax()}")


# ---- MAIN ----

analyze(Playerstats)

